export const TODO_ERROR_CODES = {
  UNAUTHORIZED: 'TODO_UNAUTHORIZED',
  VALIDATION_FAILED: 'TODO_VALIDATION_FAILED',
  NOT_FOUND: 'TODO_NOT_FOUND',
  CREATE_FAILED: 'TODO_CREATE_FAILED',
  UPDATE_FAILED: 'TODO_UPDATE_FAILED',
  DELETE_FAILED: 'TODO_DELETE_FAILED'
} as const;
